defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: atos_slurm
- graph: encoder_decoder_only
- model: transformer
- training: default
- _self_

config_validation: False

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

data: 
  resolution: o96
  diagnostic:
    - tp

  imputer:
    default: "none"
    0:
      - tp
    # mean:
    #   - tp

  processors:
    imputer:
      # _target_: anemoi.models.preprocessing.imputer.DynamicInputImputer
      # _convert_: all
      # config: ${data.imputer}
      _target_: anemoi.models.preprocessing.imputer.DynamicConstantImputer
      _convert_: all
      config: ${data.imputer}
    normalizer:
      _target_: anemoi.models.preprocessing.normalizer.InputNormalizer
      config: ${data.normalizer}


# LOAD EXTRA VARIABLES FROM OPERA
# dataloader:
#   training:
#     dataset:
#       join:
#       - dataset: ${hardware.paths.data}/${hardware.files.dataset}
#         start: 2015
#         end: 2015
#         frequency: ${data.frequency}
#         drop:  []
#       - dataset: ${hardware.paths.opera}/${hardware.files.opera}
#         rename:
#           tp: tp_radar
#         start: 2015
#         end: 2015
#         frequency: ${data.frequency}
#         drop:  []
#       adjust: dates
#     start: 2015-01-01
#     end: 2015-02-01
#     drop: []

  # validation:
  #   dataset:
  #     join:
  #     - dataset: ${hardware.paths.data}/${hardware.files.dataset}
  #       start: 2015
  #       end: 2015
  #       frequency: ${data.frequency}
  #       drop:  []
  #     - dataset: ${hardware.paths.opera}/${hardware.files.opera}
  #       rename:
  #         tp: tp_radar
  #       start: 2015
  #       end: 2015
  #       frequency: ${data.frequency}
  #       drop:  []
  #     adjust: dates
  #   start: 2015-01-01
  #   end: 2015-02-01
  #   drop: []


# CUTOUT TP OPERA-ERA5
dataloader:
  dataset:
    - dataset: #/home/mlx/ai-ml/datasets/stable/aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6.zarr
        complement:
            dataset:
              cutout:
                #- /home/ecm2559/dev_perm/anemoi-ecmwf-rodeo-benchmark/opera_2km_dataset/anemoi-datasets-configs/datasets/opera_6hr_2015_cutout_meters_o96.zarr
                - dataset: /home/ecm2559/dev_perm/anemoi-ecmwf-rodeo-benchmark/opera_2km_dataset/anemoi-datasets-configs/datasets/opera_o96_2015_6hr_global.zarr
                  area:
                      - 70
                      - -10
                      - - 20
                      - 70
                - dataset: /home/mlx/ai-ml/datasets/stable/aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6.zarr
                  select: [ tp ]
              min_distance_km: 1
              adjust: dates
        source: /home/mlx/ai-ml/datasets/stable/aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6.zarr
        interpolation: nearest
      statistics: /home/mlx/ai-ml/datasets/stable/aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6.zarr


  training:
    dataset: ${dataloader.dataset}
    start: 2015-01-01
    end: 2015-12-31
    drop: []

  validation:
    dataset: ${dataloader.dataset}
    start: 2015-01-01
    end: 2015-12-31
    drop: []


  limit_batches:
    training: null
    validation: null
    # training: 10
    # validation: 10

diagnostics:
  log:
    mlflow:
      enabled: True
      offline: False
      experiment_name: 'opera_aifs_cutout'
      project_name: 'AIFS'
      run_name: 'opera_6hr'
      tracking_uri: 'https://mlflow-test.ecmwf.int'
      authentication: True
      terminal: True
      expand_hyperparams: [] # Which keys in hyperparams to expand
    wandb:
      entity: 'ecmwf'
hardware:
  paths:
    opera: /home/ecm2559/dev_perm/anemoi-ecmwf-rodeo-benchmark/opera_2km_dataset/anemoi-datasets-configs/datasets
  files:
    opera: opera_o96_2015_6hr_global.zarr
    graph: opera_era5_o96.pt

model:
  num_channels: 512

training:
  max_steps: 10000
  max_epochs: 100
  num_sanity_val_steps: 6




